### ISSUE TITLE
Envio de camada de mapa

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#13]
O administrador poderá subir até 5 camadas em formato geojson com estilo incorporado na plataforma.

**Comment by vgeorge** [comment]
Depende de https://github.com/aetrapp/api/issues/50

**Comment by vgeorge** [comment]
@miguelpeixe te marquei aqui porque, apesar de ainda não ser possível salvar a ordenação, já dá para enviar camadas.

**Comment by vgeorge** [comment]
Feito o deploy. @odascatolini, para testar recomendo criar um mapa no [geojson.io](http://geojson.io), aplicar estilos e subir na plataforma. Não se esqueça de atualizar o navegador com Ctrl + Shift + R para ter a última versão do Webapp.

**Comment by odascatolini** [comment]
@miguelpeixe 

Ontem tentei testar as camadas, consegui subir algo em princípio, depois não mais. O sistema ficou totalmente instável, hoje o Vitor descobriu que as camadas enviadas eram muito pesadas e estavam tornando o sistema instável, então as apagou.

Peço por gentileza que verifique o problema e nos oriente melhor sobre como fazer os testes, como aplicar estilos, como editar as camadas. Estamos no meio do piloto com muitas demandas, não dá para parar agora para estudar isso, e não queremos atrasar a aprovação dos produtos de vocês. Obrigado.

**Comment by vgeorge** [comment]
O envio de camadas foi modificado. O que aconteceu anteriormente é que não havia resposta da interface enquanto estava sendo enviado uma camada, o que fez com que dezenas de camadas fossem enviadas. Agora a interface informa quando o envio da camada se inicia e termina, evitando que a mesma camada sejam enviada diversas vezes. Também foi aplicada simplificação de geometrias para diminuir o peso das camadas com detalhes em demasia.

Fizemos testes com 5 camadas de até 5 Mb e não houve lentidão nos cenários que conseguimos criar. Dado que o maior arquivo de bairros que encontramos, o de distritos de SP, tem aproximadamente 5 Mb, a plataforma deve funcionar ok com geometrias de bairros de até 5 cidades.

**Comment by odascatolini** [comment]
@vgeorge @miguelpeixe 

Tentei enviar um arquivo de 1.2Mb:

Fonte:  http://dados.gov.br/dataset/acs_equipes

Arquivo: http://i3geo.saude.gov.br/i3geo/ogc.php?service=WFS&version=1.0.0&request=GetFeature&typeName=acs_equipes&outputFormat=JSON

Esse arquivo abriu normalmente no http://geojson.io, mas no painel do AeTrapp gerou lentidão e travou o sistema. Depois de algumas tentativas consegui apagar a camada.

**Comment by miguelpeixe** [comment]
@odascatolini 

Não importa muito o tamanho do arquivo em bytes, o problema deste arquivo é que tem mais de 5 mil pontos. Mesmo no geojson.io ele fica com lentidão na navegação do mapa, menos que o aplicativo porque o geojson.io não tem outros recursos além do mapa. No caso do aplicativo, como existem outras funcionalidades, essa renderização compartilha recursos com outras coisas, causando problemas.

Para suportar múltiplos pontos implementamos um clusterizador, que será utilizado automaticamente caso as feições da camada contenha um número de **pontos** maior que 200, o resultado é esse:

![screen shot 2018-05-23 at 12 33 47](https://user-images.githubusercontent.com/820752/40435044-290e2a20-5e86-11e8-92f6-aace66fd3800.png)

O clusterizador não trabalha com feições de tipo polígono e linha. Para esses casos há uma simplificação da geometria no backend, mas se o número de feições destes tipos também for muito grande também pode causar lentidão.

É importante ressaltar que a solução GeoJSON não é feita para uma quantidade tão grande de feições, para suportar qualquer cenário é necessário o desenvolvimento de uma solução bem mais sofisticada, não contemplada no projeto.

**Comment by odascatolini** [comment]
@miguelpeixe Ficou ótimo com essa clusterização, entendemos as limitações do Geojson mas por enquanto essa funcionalidade está suficiente.
