### ISSUE TITLE
Formulários para email tokens 

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#18]
Está implementado na API o envio de tokens por e-mail. É preciso adicionar ao webapp páginas de verificação de tokens para as seguintes atividades:

- [x] confirmação de email;
- [x] redefinição de senha;
- [x] confirmação de alteração de email.

Está sendo usado o módulo [feathers-authentication-management](https://github.com/feathers-plus/feathers-authentication-management), que ajuda a configurar o serviço de gerenciamento de autenticações. 

Exemplos de chamadas na API:

- redefinição de senha:

```
curl -X POST -H 'Content-Type: application/json' -d '{"action": "sendResetPwd", "value": {"email": "seu@email.org"}}' http://localhost:3030/authManagement
```

- enviar novamente confirmação de e-mail:

```
curl -X POST -H 'Content-Type: application/json' -d '{"action": "resendVerifySignup", "value": {"email": "seu@email.org"}}' http://localhost:3030/authManagement
```

É possível usar o feathers-client normalmente acessando o serviço 'authManagement', como foi feito aqui:

https://github.com/aetrapp/mobile/blob/before-mapbox-gl/src/screens/profile/edit/Password.js#L64-L90

**Comment by miguelpeixe** [comment]
5279217717a04144cb585cec00a26560dd574c0f
