### ISSUE TITLE
Exibir campos na tabela de armadilha

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#21]
@odascatolini, no feedback que você sugeriu os seguintes campos para a tabela de armadilha:

ID armadilha; Município*; UF*; Bairro*; Endereço; Colaborador; Telefone; Celular; Número de amostras*; Última amostra (numero de ovos)*; Situação*;

Mas a lista e página de armadilha é pública, e aí não podemos colocar os dados do usuário. Na página da armadilha, se o usuário estiver logado e tiver função de moderador ou admin, ele poderá ver o link para o usuário, ok?

**Comment by odascatolini** [comment]
Oi Vitor, a necessidade aqui é facilitar a vida dos moderadores da Secretaria de Saúde, então o ideal seria ter uma visualização aberta diferente da visualização de moderadores e administradores

**Comment by vgeorge** [comment]
@miguelpeixe Será necessário adicionar à tabela uma coluna de usuários se o usuário tiver role admin/moderador. O conteúdo da coluna pode ser `João (11) 99999-9999`, ou seja, primeiro nome e celular, com link para a página do usuário.

**Comment by vgeorge** [comment]
@odascatolini A sugestão que dei acima é adequada?

**Comment by odascatolini** [comment]
@vgeorge 

Para facilitar o acompanhamento, os usuários devem poder ver os seguintes dados na tela de armadilhas:

Admin/moderador

ID armadilha; Município*; UF*; Bairro*; Endereço; Colaborador; Telefone; Celular; **Email** (havia esquecido); Número de amostras*; Última amostra (numero de ovos); Situação;

Outros

ID armadilha; Município*; UF*; Bairro*; Endereço; Número de amostras*; Última amostra (numero de ovos); Situação;

**Comment by miguelpeixe** [comment]
@odascatolini 

No caso de admin incluímos o nome e link do usuário responsável, onde contém todas as informações. A tabela ficaria com leitura bastante prejudicada incluindo todas as colunas mencionadas, por isso sugiro não incluirmos os metadados relativos ao responsável, apenas seu nome e link.

**Comment by odascatolini** [comment]
@miguelpeixe 

Temos que pensar esse dashboard para usuários que não tenham condições de baixar as tabelas, montar um banco de dados, montar seus próprios filtros e visualizar no QGIS. No caso desse perfil de usuário, a usabilidade seria facilitada se o usuário pudesse ver os dados que necessita sem ter que clicar em um por um. 

Fica difícil visualizar a interface sem estar implementada para avaliar se a leitura ficaria difícil.

De todo modo entendemos seu ponto, uma alternativa seria fazer da forma que você sugere, desde que os filtros aplicados no webapp sejam aplicados também no download da tabela csv, e que essa venha com os dados completos.

**Comment by odascatolini** [comment]
@vgeorge já foi comentado acima

**Comment by vgeorge** [comment]
Conversei com @odascatolini e com a habilitação de filtros no download de CSV não será necessário alterar mais as colunas.

**Comment by odascatolini** [comment]
Está para review mas não implementado

**Comment by odascatolini** [comment]
Vou fechar essa e acompanhar pela #36
