### ISSUE TITLE
Página de usuários

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#24]
Campos:

- [x] ID usuário; 
- [x] Nome; 
- [ ] Município*; 
- [ ] UF*; 
- [ ] Bairro*; 
- [x] Telefone; 
- [x] Celular; 
- [x] Email; 
- [x] Número de armadilhas ativas*; 
- [ ] Armadilha atrasada? (sim/não)*; 
- [x] função; 
- [x] ações;

**Comment by miguelpeixe** [comment]
- Campos município, uf e bairro não existem para usuário.
 - Backend não retorna as informações "nº de armadilhas ativas" e "armadilha atrasada".
  1. **backend deve conter a lógica para permitir a ordenação** e
  2. é altamente preferível que também contenha a lógica para exibir essa informação, já que de outra forma seria necessário fazer 1 request a mais para cada item da lista.

**Comment by vgeorge** [comment]
Depende de:

- Rota de download de usuários: https://github.com/aetrapp/aetrapp/issues/35
- Popular usuário com armadilhas: https://github.com/aetrapp/aetrapp/issues/36

**Comment by vgeorge** [comment]
Rota de download está disponível e protegida para admins, aqui tem um exemplo de como acessar: 

https://github.com/aetrapp/aetrapp/blob/master/src/services/downloads/downloads.service.js#L116-L126

**Comment by miguelpeixe** [comment]
cc @vgeorge 

Retornar sobre validade do campo "Amardilha atrasada" e asteríscos assinalados nos itens da lista

**Comment by vgeorge** [comment]
@odascatolini 

O usuário não tem informações de localidade, somente armadilhas tem. Sobre a informação de que ele tem armadilhas atrasadas, isso depende de outra issue que está a implementação https://github.com/aetrapp/aetrapp/issues/41. Vou colocar para revisão de qualquer maneira para você verificar a situação atual.

**Comment by odascatolini** [comment]
@vgeorge 

Ok, aguardando a implementação da info de armadilhas atrasadas

**Comment by vgeorge** [comment]
@miguelpeixe O back end agora retorna a contagem de armadilhas atrasadas.

**Comment by odascatolini** [comment]
Botão "Exportar usuários" não funciona

Filtro "Com armadilhas" não bate com a coluna número de armadilhas

**Comment by vgeorge** [comment]
@miguelpeixe O botão de exportação está funcionando, mas o filtro "com armadilhas" parece que não está.

**Comment by miguelpeixe** [comment]
@vgeorge parece estar funcionando aqui, a query é simples: 

```json
{
  trapCount: { $gte: 1 }
}
```

Em REST seria: http://api.aetrapp.org/users?trapCount%5B%24gte%5D=1

**Comment by miguelpeixe** [comment]
@vgeorge Ordenação por numero de armadilhas não retorna ordenação correta. Requisição rest: http://api.aetrapp.org/users?$sort[trapCount]=-1

**Comment by miguelpeixe** [comment]
Sistema de ordenação via click no cabeçalho da tabela foi implementado, aguardando atualização sobre problema mencionado acima.

**Comment by vgeorge** [comment]
O problema é que havia usuários com trapCount nulo no banco em produção, já corrigi.

**Comment by odascatolini** [comment]
@miguelpeixe 


Está ok, mas o ícone só aparece quando clicamos no cabeçalho da coluna, então somente quem sabe da funcionalidade vai poder clicar. Favor exibir sempre

**Comment by odascatolini** [comment]
@miguelpeixe 

Os ícones para ordenamento no cabeçalho das tabelas continuam não aparecendo aqui

**Comment by vgeorge** [comment]
Uma nova versão está no ar.

**Comment by odascatolini** [comment]
ok
