### ISSUE TITLE
Adicionar busca por email e ID usuário

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#25]
@odascatolini, em que casos faz sentido buscar pelo id do usuário? Parece que a busca pelo e-mail do usuário é suficiente.

**Comment by miguelpeixe** [comment]
Busca por ID já incluída

**Comment by miguelpeixe** [comment]
Email também

**Comment by odascatolini** [comment]
Ok obrigado.

**Comment by vgeorge** [comment]
@odascatolini  Se você estiver no waffle tem que clicar no balão de conversa e lá embaixo há o botão "close issue". No github tem o mesmo botão, que ao editar comentário tem o título "Close and comment".
