### ISSUE TITLE
Página do Mapa

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#29]
Filtrar por situação - deve ter as situações: aguardando primeira amostra; sem ovos; abaixo da média; na média; acima da média; amostra atrasada; desativada

Os pins devem ter as cores relacionadas às situações

**Comment by miguelpeixe** [comment]
Filtro deve ser fornecido via backend

**Comment by vgeorge** [comment]
Depende de https://github.com/aetrapp/aetrapp/issues/39

**Comment by vgeorge** [comment]
Tentei de várias maneiras, mas ficou muito complexo fazer a implementação de filtros por status via backend devido a limitações de sequelize. 

Para tentar resolver a questão, adicionei um after hook ao serviço de cidade que coloca a propriedade `currentMeanCount` nas cidades onde existe contagem válida na semana corrente, e aí dá para comparar a armadilha com a média da cidade, se houver. 

Também coloquei um after hook nas armadilhas que adiciona a propriedade `isDelayed` caso a armadilha esteja ativa e o ciclo já chegou ao seu final.

**Comment by vgeorge** [comment]
Aqui estão faltando ser possível os filtros na API.

**Comment by vgeorge** [comment]
@miguelpeixe O campo de status está disponível agora para filtro, favor verificar.

**Comment by odascatolini** [comment]
- Os pins devem ter as cores relacionadas às situações

- Falta a situação "atrasada"nos filtros

**Comment by vgeorge** [comment]
O status `delayed` está em vigor e as cores são essas:

```
  black: "#010101", // "inactive"
  gray: "#818181", // "delayed"
  blue: "#006AB8", // "waiting-sample"
  green: "#059C3F", //"no-eggs"
  red: "#EB604D", // "above-average"
  yellow: "#FAEC01" // "bellow-average"
```

@miguelpeixe se faltar alguma informação, me avise.

**Comment by odascatolini** [comment]
@miguelpeixe 

Favor tocar "aguardando amostra" por "aguardando primeira amostra", como no mobile

**Comment by miguelpeixe** [comment]
Pode me exibir um exemplo @odascatolini ?

**Comment by vgeorge** [comment]
@miguelpeixe Aqui o problema que o Oda se refere é de backend, pois a situação das armadilhas não está sendo atualizada corretamente.

**Comment by miguelpeixe** [comment]
Ok

**Comment by vgeorge** [comment]
A lógica de definição de status das armadilhas foi revisada e o problema não era específico desta issue, então vou fechar esta issue. Se persistir algum erro, por favor, abra uma issue específica para ele.
