### ISSUE TITLE
Broadcast por cidades

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#3]
O moderador poderá enviar broadcast para as cidades às quais tem acesso.

**Comment by miguelpeixe** [comment]
Broadcast será enviado via serviço de notificação? A especificação está conflitante https://github.com/aetrapp/aetrapp/issues/30

**Comment by miguelpeixe** [comment]
Implementado formulário com campos:

 - Título
 - Mensagem
 - Cidades
   - Em caso de administrador, campo permite busca e múltipla seleção por todas as cidades ou vazio para envio global;
   - Em caso de moderador responsável por **apenas uma** cidade é realizado preenchimento automático e não exibe campo;
   - Em caso de moderador responsável por **múltiplas** cidades é exibido campo para seleção de qual(is) cidade(s) enviar mensagem. É exibido erro em caso de seleção vazia.
 - Data de envio
   - Date time picker opcional
