### ISSUE TITLE
Página de Amostras

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#30]
Mudar nome de Coleta para Amostras

Enxugar data e hora para o formato “02/03/2018 - 16:20”

Colocar colunas: “Id Usuário” (com link para usuário), “Id armadilha” (com link para armadilha), “Id Amostra”, Município

Status - Traduzir para português

**Comment by miguelpeixe** [comment]
Ok

**Comment by miguelpeixe** [comment]
cc @vgeorge validar

**Comment by vgeorge** [comment]
A página deve ser revisada porque foi removido o campo addressNumber, pois é melhor que o usuário digite junto ao endereço.

**Comment by vgeorge** [comment]
Apaguei o comentário anterior, confundi com a página de armadilhas. Falta colocar o nome do usuário no link.

**Comment by miguelpeixe** [comment]
Para obter o nome o usuário precisa estar populado no objeto da amostra

**Comment by miguelpeixe** [comment]
cc @vgeorge

**Comment by vgeorge** [comment]
Agora os métodos FIND and GET estão populados com o nome do usuário, caso ele exista no sistema.

**Comment by vgeorge** [comment]
Está estranha a exibição da data da amostra:

![captura de tela 2018-04-12 as 09 32 45](https://user-images.githubusercontent.com/329694/38677412-9b511fd8-3e34-11e8-81ef-295110ef2295.png)

**Comment by odascatolini** [comment]
@vgeorge 

1- Qual a diferença entre "inválidas" e "com erros"?

2- Os totais não batem:
todas: 40
validas: 21
Invalidas: 15
Com erros: 16

3 - Ao aplicar o filtro "com erros" não é possível aplicar o filtro "todas"

4- Falta coluna e filtro por município/uf

5- Falta o botão baixar amostras (baixar tabela completa com os filtros aplicados)

**Comment by miguelpeixe** [comment]
@odascatolini não entendi o item 4, município e uf estão nas colunas e o filtro por cidade está disponível

item 3 está corrigido, falta apenas fazer o deploy

cc @vgeorge a respeito do item 1, 2 e 5

**Comment by miguelpeixe** [comment]
Ok, entendi o item 4, me confundi com a página de amostras.

@vgeorge avalie isso

**Comment by odascatolini** [comment]
aguardando:

1- Qual a diferença entre "inválidas" e "com erros"?

2- Os totais não batem:
todas: 40
validas: 21
Invalidas: 15
Com erros: 16

4- Falta coluna e filtro por município/uf

5- Falta o botão baixar amostras (baixar tabela completa com os filtros aplicados)

**Comment by odascatolini** [comment]
@miguelpeixe 

Botão ok, mas os filtros ainda não foram aplicados no cdv

Aguardando isso e 1 a 4

**Comment by vgeorge** [comment]
@miguelpeixe Esclarecendo sobre o status de amostras:

- `unprocessed`: situação padrão da amostra após sua criação;
- `analysing`: em análise pelo Image Processing Service;
- `valid`: analisada com sucesso, deve ter contagem de ovos definida;
- `invalid`: houve algum problema na análise, o erro é relatado no campo `error`.

Sobre a ordenação por cidades, depende de https://github.com/aetrapp/api/issues/44.

O download do CSV depende de https://github.com/aetrapp/api/issues/45.

**Comment by vgeorge** [comment]
@miguelpeixe As issues de back-end foram resolvidas, verifique as issues correspondentes para saber como usar as rotas.

**Comment by miguelpeixe** [comment]
Para ordenação de amostras via cidade da forma sugerida por @odascatolini (click no cabeçalho da tabela) é necessário popular o  resultado das amostras com as informações cidade.

**Comment by miguelpeixe** [comment]
Sistema de ordenação via click no cabeçalho da tabela foi implementado, aguardando atualização sobre ordenação por cidade.

**Comment by vgeorge** [comment]
@odascatolini As amostras não estão relacionadas diretamente às cidades, apenas às armadilhas. Aqui será necessária uma alteração do back end que está relatada aqui https://github.com/aetrapp/api/issues/49

**Comment by vgeorge** [comment]
Depende de https://github.com/aetrapp/api/issues/49

**Comment by vgeorge** [comment]
Foram feitas mudanças na API que permitem o ordenamento de amostras por cidades. Qualquer problema com a API, por favor, reportar em https://github.com/aetrapp/api/issues/49.

**Comment by miguelpeixe** [comment]
Implementado em https://github.com/aetrapp/webapp/commit/c1e78ce8fa4778f0be30b42a590e48260d7753cd

**Comment by odascatolini** [comment]
@vgeorge @miguelpeixe 

Nessa página ainda há um ponto a resolver:

1- Qual a diferença entre "inválidas" e "com erros"? Ambos filtros retornam o mesmo resultado.

**Comment by odascatolini** [comment]
ok
