### ISSUE TITLE
Renomear "Coleta" para "Amostras" 

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#31]
O termo adotado agora é amostras e todas as ocorrências de coletas devem ser substituídas.

**Comment by miguelpeixe** [comment]
Ok

**Comment by odascatolini** [comment]
@vgeorge @miguelpeixe 

Ainda aparece em alguns lugares com coleta e em outros como amostra.

Ex: http://aetrapp-web.aparabolica.com.br/traps/SJilTyiwG

Foram realizadas 1 coletas nesta armadilha / Nesse caso específico seria melhor: "Foi coletada 1 amostra nesta armadilha"

35 OVOS ENCONTRADOS NA ÚLTIMA COLETA / correto: ULTIMA AMOSTRA

Última coleta realizada 20 dias atrás / correto: Última amostra
