### ISSUE TITLE
Painel não está funcionando

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/webapp#32]
@vgeorge @miguelpeixe Conforme já informado por email, o painel continua abrindo na página principal, mas ficando em branco ao clivarmos em qualquer menu ou armadilha no mapa, impossibilitando revisão e testes

**Comment by vgeorge** [comment]
Fiz deploy de correções, verifique novamente, por favor.

**Comment by odascatolini** [comment]
@vgeorge voltou a funcionar, obrigado
