### ISSUE TITLE
Tela de Notificações

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/webapp#35]
- As notificações não estão sendo recebidas no app

- Em usuário específico, fazer a busca por email ao invés de nome, pois com nomes repetidos não dá para distinguir usuários (pesquisem "oda" para entender, e imaginem João da Silva ou outros nomes com muitos homônimos)

**Comment by miguelpeixe** [comment]
Email foi adicionado como campo buscável no "broadcast", além de exibir o email nos resultados encontrados para facilitar seleção.

cc @vgeorge sobre notificações não estarem sendo recebidas no app

**Comment by odascatolini** [comment]
@miguelpeixe @vgeorge 

Busca por email ok.

Favor mudar:

"Selecione o usuário que receberá a mensagem"

por 

"Selecione o usuário que receberá a mensagem (busca por email)"

Quanto às mensagens, enviei mensagem individual para mim mesmo e geral para todos e recebi ambas no app, só falta o push.

Mas o envio para usuários que tenham armadilha no município X não funciona, tentei com Brasília e Recife e não recebi.

Outro ajuste: após envio de uma mensagem o navegador volta para o mapa, não permanece na tela de notificações.

**Comment by vgeorge** [comment]
Sobre as notificações, vamos dar seguimento em issues específicas:

- Notificações para cidades https://github.com/aetrapp/api/issues/43 
- Notificações push para broadcasts https://github.com/aetrapp/api/issues/42 

Então, ficou faltando ajustar no webapp:

- Alterar a mensagem como descrito acima;
- Permanecer na tela de notificações após o envio.

**Comment by odascatolini** [comment]
ok
