### ISSUE TITLE
Gráfico da armadilha deve estender a média de contagens até o dia atual

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#39]
A média de contagens da última semana deve ser estendida no gráfico da armadilha até o dia atual, facilitar a comparação com contagens da semana em aberto e evitar que exista sempre uma parte em branco no gráfico.

**Comment by vgeorge** [comment]
Depende do cenário em produção ou de https://github.com/aetrapp/api/issues/51.

**Comment by miguelpeixe** [comment]
Isso não seria um dado inconsistente? Se a média da semana se refere à dados contidos naquela semana, não acho que o dado pode deliberadamente se extender à "hoje".

**Comment by odascatolini** [comment]
ok!
