### ISSUE TITLE
Gráfico com problema de escala quando contagem coincide com início do ciclo

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#41]
No exemplo abaixo foram enviadas amostras nas segunda-feiras e os valores estão se repetindo no eixo x (18/03, 25/03, etc):

![captura de tela 2018-04-22 as 22 07 58](https://user-images.githubusercontent.com/329694/39102412-fff18b4c-4679-11e8-89d5-f2f915fdc234.png)

Parece que quando o envio da armadilha coincide com o início do ciclo o valor é duplicado no eixo.

O gráfico é da armadilha do link abaixo, que pode ser que mude porque outras amostras serão enviadas:

http://painel.aetrapp.org/traps/PR62N6AVUNKX3

**Comment by miguelpeixe** [comment]
Novo gráfico:

![screen shot 2018-04-23 at 12 26 44](https://user-images.githubusercontent.com/820752/39136486-b8a6e78c-46f1-11e8-887b-ce3218b31efc.png)

**Comment by odascatolini** [comment]
ok
