### ISSUE TITLE
Legenda do mapa

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#43]
A legenda do mapa deve exibir a relação entre cores e status.

**Comment by odascatolini** [comment]
@vgeorge 

Ficou legal, só precisa ajustar "Aguardando amostra" para "Aguardando 1a amostra". valeu!

**Comment by odascatolini** [comment]
@miguelpeixe 

Considerando que as camadas adicionais serão cliváveis acima da legenda do mapa, favor fazer com que o mesmo sistema seja aplicado na legenda, com as cores de armadilhas sendo clicáveis também. Senão fica confuso para o usuário filtrar/adicionar camadas em dois lugares (lá em cima em filtrar por situação e na legenda para camadas adicionais). Obrigado.

**Comment by vgeorge** [comment]
Uma nova versão está no ar.

**Comment by odascatolini** [comment]
ok
