### ISSUE TITLE
Exibir data da próxima coleta nas armadilhas

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/webapp#45]
Exibir data da próxima coleta nas armadilhas (lista de armadilhas e página de armadilha)

**Comment by vgeorge** [comment]
A interface da página de armadilhas para esta etapa do desenvolvimento foi fechada nesta issue: https://github.com/aetrapp/webapp/issues/20. A adição desta coluna deverá em nova etapa de desenvolvimento do projeto. Criei a tag `future versions` para as funcionalidades que se encaixam neste perfil.

**Comment by odascatolini** [comment]
@vgeorge consideramos essa funcionalidade fundamental para moderação e administração, como está hoje apenas o próprio usuário sabe a data de fotografia

**Comment by miguelpeixe** [comment]
Implementado em 52608f6e08dd0bd0c0c7e835656594ccdf93bb6c

![screen shot 2018-06-19 at 15 58 27](https://user-images.githubusercontent.com/820752/41618523-c59c9fda-73d9-11e8-8baa-7f55d3245f51.png)

![screen shot 2018-06-19 at 15 58 36](https://user-images.githubusercontent.com/820752/41618524-c7d8721a-73d9-11e8-9a29-4a3eead84836.png)

**Comment by odascatolini** [comment]
ok
