### ISSUE TITLE
Lentidão ao carregar armadilhas e amostras

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#47]
A interface está apresentando lentidão ao carregar as tabelas de armadilhas e amostras. Imagino que possa ser pelo uso do populate nas chamadas. Sugiro testar passar `skipResolve: true` nestas chamadas para ver se o problema é resolvido.

**Comment by miguelpeixe** [comment]
Não fui capaz de reproduzir essa lentidão, o tempo para exibição de ambas tabelas são poucos milissegundos.

**Comment by vgeorge** [comment]
Na maioria dos casos o cliente carrega rápido, mas tem pelo menos uma situação em que demora a carregar. Testando no Chrome, sem estar logado, ao alternar entre o mapa e a aba de armadilha, a tabela de armadilha carrega lentamente.

**Comment by vgeorge** [comment]
Não consegui reproduzir o problema, parece que foi sanado.
