### ISSUE TITLE
Edição/Remoção de armadilhas

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/webapp#48]
O administrador deve poder remover armadilhas ou:

- editar endereço e coordenadas;
- marcar armadilha como inativa;
- enviar nova foto de armadilha.

**Comment by odascatolini** [comment]
ok

**Comment by odascatolini** [comment]
A idéia é fechar essa issue e acompanhar pela #44 ?

**Comment by odascatolini** [comment]
ok

**Comment by miguelpeixe** [comment]
Página de edição da armadilha está disponível no repositório. Pendente deploy e correção na API para permitir que a imagem possa ser enviada via `patch` (verificação da propriedade base64 no envio através deste método para execução do hook `storeBlob`). https://github.com/aetrapp/api/blob/master/src/services/traps/traps.hooks.js#L254-L264

![screen shot 2018-06-19 at 14 21 33](https://user-images.githubusercontent.com/820752/41613495-1c5e69b0-73cc-11e8-8bc2-d59ab421e22b.png)


![screen shot 2018-06-19 at 14 17 00](https://user-images.githubusercontent.com/820752/41613396-da9413fe-73cb-11e8-9de7-305a63f3ef8c.png)

**Comment by vgeorge** [comment]
Feito.

**Comment by odascatolini** [comment]
ok
