### ISSUE TITLE
Problema com status das armadilhas

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/webapp#49]
Há armadilhas em dia com status de atrasadas, ex:

5NAAA4XJ84BY6

**Comment by odascatolini** [comment]
Urgente

**Comment by vgeorge** [comment]
Parece que voltou ao normal:

http://painel.aetrapp.org/traps/5NAAA4XJ84BY6

**Comment by odascatolini** [comment]
@vgeorge 

Repare que nessa do link acima, a ultima fotografia foi há 8 dias e o status está "aguardando 1a amostra".

**Comment by miguelpeixe** [comment]
@vgeorge @odascatolini  acho que a questão é que o status `waiting-sample` não se refere só a **primeira** amostra da armadilha, se refere também a armadilhas que tiveram seu ciclo reiniciado. Se for o caso, o texto deverá ser alterado para "Aguardando amostra", correto?

**Comment by vgeorge** [comment]
Sim, com a alteração do processo de avaliação de status da armadilha não existe o status 'aguardando primeira amostra'. 

@odascatolini Sobre a armadilha acima, provavelmente o usuário iniciou novo ciclo e aí ela não deveria estar atrasada mesmo. Mas vamos observar.

**Comment by odascatolini** [comment]
@vgeorge @miguelpeixe 

Considerando que não existe mais o status 'aguardando primeira amostra', é preciso modificar para "aguardando amostra" em todo o sistema (webapp e app). Na legenda do mapa (filtros) ainda aparece como 'aguardando primeira amostra' por exemplo.

**Comment by miguelpeixe** [comment]
Corrigido em todas as ocorrências do webapp

**Comment by odascatolini** [comment]
ok
