### ISSUE TITLE
Dois pontos no gráfico para um mesmo dia

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/webapp#52]
@vgeorge @miguelpeixe 

Vejam nesse exemplo:

http://painel.aetrapp.org/traps/U8QVNNAQPVQCF

Há duas amostras representadas no gráfico no mesmo dia, deveria aparecer apenas a última.

**Comment by vgeorge** [comment]
Não é um problema do webapp, os dados existem no banco e parece ser um problema da API. Criei a issue no repositório correspondente:

https://github.com/aetrapp/api/issues/59
